### ISSUE TITLE
Repetition

### ISSUE THREAD

**Issue by lubegasimon** [freelyformd/eval-cso#192]
Is  [this](https://github.com/freelyformd/eval-cso/blob/4dc50adc15ea25b551b99e7e647a347bbc02eb2d/src/views/components/EvaluationForm/index.tsx#L265) really needed because we didn't reassign it anywhere in the [handleSubmit function ](https://github.com/freelyformd/eval-cso/blob/4dc50adc15ea25b551b99e7e647a347bbc02eb2d/src/views/components/EvaluationForm/index.tsx#L250) it's already catered for [here](https://github.com/freelyformd/eval-cso/blob/4dc50adc15ea25b551b99e7e647a347bbc02eb2d/src/views/components/EvaluationForm/index.tsx#L260)

**Comment by epicallan** [comment]
No it's not needed. You can submit a PR for it.

**Comment by lubegasimon** [comment]
do you think it could be the reason for this ?
![WhatsApp Image 2019-07-19 at 17 56 20](https://user-images.githubusercontent.com/34124177/61544721-b0afe800-aa4e-11e9-8404-4334b512e7f4.jpeg)

**Comment by epicallan** [comment]
No, they were referring to phone numbers that had more than 9 digits i.e 256771... 
You can ignore it as its solved by your earlier PR on customer Telephone input field.
