### ISSUE TITLE
Enter evaluation data UI form

### ISSUE THREAD

**Issue by epicallan** [freelyformd/eval-cso#29]
parent #26 

We need to create a form where evaluators can enter performance evaluation data for an agent.

The form will have the same fields as the ones below with some alterations.

<img width="662" alt="Screen Shot 2019-03-25 at 5 01 07 PM" src="https://user-images.githubusercontent.com/6281527/54927702-baec2a80-4f23-11e9-8d5f-d258e7dd9d90.png">

Alteration to make:

- Submit Date field is a calendar widget whose default data is today
- Agent name field shows a scrollable dropdown of agent names that are selectable by clicking on them when in focus.
- The agent Name field is a searchable field, i.e. When you start typing a user name, a dropdown of names appears with names beginning with the letters that have been typed.
The Agent Name field is a bit complex; I advise to build it as an isolated component of its own within a sub-issue of its own.(#33)

- Submit and close buttons are on the same line horizontally and bellow comment field.

Implementation notes:

Reasons for deviating and reasons for Zero rating are evaluation quality parameter groupings. So from the server expect a resource of this sort:

```
{
  evaluationType: "call"
  agents: string[]
  parameterCatergories: [
  {
     name: "Reasons for zero rating",
     value:  "zero_rated",
     parameters: [{name"Breach of confidentiality", value "breach_of_confidentiality"}, ....],
   },
   {
     name: "Reasons for deviating"
     value:  "deviation",
     parameters: [{name"Acknowledgment", value "acknoledgement"}, ....]
   }   
  ]
```

The structure of the server resource data means you will have a parameter categories prop to construct the reasons for deviation and reasons for zero-rating fields as in the screenshot. 
The titles of the fields will also come from the server.

The `reason field` name will also be constructed by concatenating `evaluation type` from the server and the word `reason`.

In your submission function, you will submit the checked parameters within their groupings and the rest of the entered data.

eg
```
{ 
  agentName: string
  reason: string;
  submitDate: string;
  evaluationType: string;
  parameterCategories: [{
      value: string;
      parameters: string[]; // checked parameters
  }]
}
```

Expected time of delivery: 3 - 5 days.

A container component for this component will be done in another task

**Comment by lubegasimon** [comment]
![Screenshot_2019-03-30 Enter evaluation data UI form · Issue #29 · freelyformd eval-cso](https://user-images.githubusercontent.com/34124177/55276594-94086c80-5306-11e9-8a51-ad10c6d96249.png)
isn't agents be an array of objects, say,
```
  agents: [
     {name: "alex", value:"Alex", key: "A"},
     {name: "brian", value:"Brian", key: "B"}
]

**Comment by epicallan** [comment]
Minor correction

The data to submit could be of this form:
```
{ 
  agentName: string
  reason: string;
  submitDate: string;
  evaluationType: string;
  // checked parameters
  parameters: string[ ]
}
```
> @epicallan, isn't agents prop supposed to be an array of objects, say,

  ```
agents: [
     {name: "alex", value:"Alex", key: "A"},
     {name: "brian", value:"Brian", key: "B"}
]
```

The agents from the props will just be a  list of strings (`agents: string[]`). It's upto you to write code that changes it into the appropriate type for presentation.

**Comment by lubegasimon** [comment]
okay, @epicallan . i have just seen this, mean while, let me submit a PR and will continue get on it
