### ISSUE TITLE
Evaluation Data view

### ISSUE THREAD

**Issue by epicallan** [freelyformd/eval-cso#31]
Parent #26 

related to #29

The data view table allows us to view filterable data without any aggregations. i.e Selecting a date range shows data in that range as individual entries even when there are more than 2 entries on a particular date.

Aim

Create a table with quality evaluation data for agents.

Description

Once an evaluator enters data regarding the quality of an agent, that data is represented as a new entry in the evaluation data view table as below.

<img width="1019" alt="Screen Shot 2019-03-25 at 10 35 40 PM" src="https://user-images.githubusercontent.com/6281527/54949030-25ff2680-4f4f-11e9-91d0-de48694128d3.png">

Orderable columns:

The AgentName and Score columns will be orderable in ascending and descending order. 

Filter widget.

We will need a filter widget bar above the table. It will include the following;
- a date field with a start and end date widget for viewing data by date range.
- an agentName input field which shows a drop down of names on typing a name. When it's in focus it shows a scrollable list of names.
- An evaluator input field with the same behaviour as the agentName input field. By default, it has the current logged in evaluator as the value input. 

The filter widget should be done as a separate issue #32 I advise you start with it.

Possible data from the server:

```
interface ParameterCategory {
  name: string
  value: string
  paremeters: Arrary<{name: string, value: string, weight: number}>
}

interface Evaluation {
  evaluator: string
  agentName: string
  parameterCategories: ParameterCategory[],
  comment: string
  score: number
}

type EvaluationData = Evaluation[ ]

// paremeterCategory example

 const parameterCatergories: ParameterCategory[] = [
  {
     name: "Reasons for zero rating",
     value:  "zero_rated",
     parameters: [{name"Breach of confidentiality", value "breach_of_confidentiality"}, ....],
   },
   {
     name: "Reasons for deviating"
     value:  "deviation",
     parameters: [{name"Acknowledgment", value "acknoledgement"}, ....]
   }   
  ]

```

**Comment by aleku399** [comment]
What about the date and  call reason

**Comment by epicallan** [comment]
Yes, add the missing fields.  There are also some changes we need to make the expected server data  which is received by the container component of the `Data view`  component

It should be more of this.
```
data EvalAttrs = EvalAttrs
  { reason :: Text
  , evaluator :: Text
  , agent :: Text
  , customer :: Int
  , comment :: Maybe Text  // (can be null)
  , duration :: Maybe Int  // (can be null)
  , date :: UTCTime
  } 

data ParameterAttrs = ParameterAttrs
  { name :: Text
  , value :: Int
  , weight :: Int
  }

data EvalRecord = EvalRecord
  { parameterAttrs :: [ParameterAttrs] // list of parameters for a particular evaluation
  ,  evalAttrs :: EvalAttrs 
  , totalScore :: Int // can also be computed from evaluation attribute weight.
 ,  category :: Text // can be "Reasons for zero rating" or "Reasons for deviation"
  }

type evalRecords = [EvalRecords] // this is the data the server sends out. Its an array of evaluation records
```
